[book]
authors = ["Ida Iyes", "andezitgq"]
language = "eo"
multilingual = false
src = "src"
title = "Neoficiala Bevy Tromplibro"

[output.html]
additional-js = ["nagbar.js"]
additional-css = ["nagbar.css", "sidebar.css"]
